version: "2.4"
services:
  data-service:
    build:
      context: ../
      dockerfile: DataStoreService/Dockerfile
    env_file: .env
    ports:
      - "5001:80"
    depends_on:
      - postgres

  business-service:
    build:
      context: ../
      dockerfile: DnDGameService/Dockerfile
    env_file: .env
    ports:
      - "5000:80"
    depends_on:
      - postgres
  
  frontend-service:
    build:
      context: ../
      dockerfile: Frontend/Dockerfile
    env_file: .env
    ports:
      - "8080:80"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:alpine
    ports:
      - "6666:5432"
    environment:
      POSTGRES_PASSWORD: fd2ee12swq
      POSTGRES_DB: dreamspb